/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ve.zoonosis.vistas;

import com.megagroup.Application;
import javax.swing.JDesktopPane;
import ve.zoonosis.model.listener.TemplateListeners;
import ve.zoonosis.model.components.InternalFrame;

/**
 *
 * @author angel.colina
 */
public class Template extends javax.swing.JFrame {

    /**
     * Creates new form Template
     */
    public Template() {
        initComponents();
        TemplateListeners.inicializarTemplate(Template.this);
        addListeners();
    }

    public void addInternalFrame(InternalFrame internalFrame) {
        FONDO.add(internalFrame);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FONDO = new javax.swing.JDesktopPane();
        menu = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenu1 = new javax.swing.JMenu();
        casos = new javax.swing.JMenuItem();
        jornadasVacunacion = new javax.swing.JMenuItem();
        novedades = new javax.swing.JMenuItem();
        javax.swing.JMenu jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        EJornadaDiarioM1 = new javax.swing.JMenuItem();
        EJornadaSemanalM1 = new javax.swing.JMenuItem();
        EJornadaMensualM1 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        EJornadaDiarioP1 = new javax.swing.JMenuItem();
        EJornadaSemanalP1 = new javax.swing.JMenuItem();
        EJornadaMensualP1 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        EJornadaDiarioM4 = new javax.swing.JMenuItem();
        EJornadaSemanalM4 = new javax.swing.JMenuItem();
        EJornadaMensualM4 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        EJornadaDiarioP4 = new javax.swing.JMenuItem();
        EJornadaSemanalP4 = new javax.swing.JMenuItem();
        EJornadaMensualP4 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        javax.swing.JMenu jMenu7 = new javax.swing.JMenu();
        EJornadaDiarioM5 = new javax.swing.JMenuItem();
        EJornadaSemanalM5 = new javax.swing.JMenuItem();
        EJornadaMensualM5 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        EJornadaDiarioP5 = new javax.swing.JMenuItem();
        EJornadaSemanalP5 = new javax.swing.JMenuItem();
        EJornadaMensualP5 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        EJornadaDiarioM6 = new javax.swing.JMenuItem();
        EJornadaSemanalM6 = new javax.swing.JMenuItem();
        EJornadaMensualM6 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        EJornadaDiarioP6 = new javax.swing.JMenuItem();
        EJornadaSemanalP6 = new javax.swing.JMenuItem();
        EJornadaMensualP6 = new javax.swing.JMenuItem();
        javax.swing.JMenu jMenu3 = new javax.swing.JMenu();
        javax.swing.JMenu opciones = new javax.swing.JMenu();
        importar = new javax.swing.JMenuItem();
        exportar = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        acercaDe = new javax.swing.JMenuItem();
        ayuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zoonosis System");
        setExtendedState(6);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        javax.swing.GroupLayout FONDOLayout = new javax.swing.GroupLayout(FONDO);
        FONDO.setLayout(FONDOLayout);
        FONDOLayout.setHorizontalGroup(
            FONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        FONDOLayout.setVerticalGroup(
            FONDOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );

        jMenu1.setText("Control");

        casos.setText("Casos");
        jMenu1.add(casos);

        jornadasVacunacion.setText("Jornadas de Vacunacion");
        jMenu1.add(jornadasVacunacion);

        novedades.setText("Novedades");
        jMenu1.add(novedades);

        menu.add(jMenu1);

        jMenu2.setText("Estadistica");

        jMenu4.setText("Casos por animales");

        EJornadaDiarioM1.setText("Diario por Municipio");
        jMenu4.add(EJornadaDiarioM1);

        EJornadaSemanalM1.setText("Semanal por Municipio");
        jMenu4.add(EJornadaSemanalM1);

        EJornadaMensualM1.setText("Mensual por Municipio");
        jMenu4.add(EJornadaMensualM1);
        jMenu4.add(jSeparator3);

        EJornadaDiarioP1.setText("Diario por Parroquia");
        jMenu4.add(EJornadaDiarioP1);

        EJornadaSemanalP1.setText("Semanal por Parroquia");
        jMenu4.add(EJornadaSemanalP1);

        EJornadaMensualP1.setText("Mensual por Parroquia");
        jMenu4.add(EJornadaMensualP1);

        jMenu2.add(jMenu4);

        jMenu13.setText("Casos por especies");

        EJornadaDiarioM4.setText("Diario por Municipio");
        jMenu13.add(EJornadaDiarioM4);

        EJornadaSemanalM4.setText("Semanal por Municipio");
        jMenu13.add(EJornadaSemanalM4);

        EJornadaMensualM4.setText("Mensual por Municipio");
        jMenu13.add(EJornadaMensualM4);
        jMenu13.add(jSeparator8);

        EJornadaDiarioP4.setText("Diario por Parroquia");
        jMenu13.add(EJornadaDiarioP4);

        EJornadaSemanalP4.setText("Semanal por Parroquia");
        jMenu13.add(EJornadaSemanalP4);

        EJornadaMensualP4.setText("Mensual por Parroquia");
        jMenu13.add(EJornadaMensualP4);

        jMenu2.add(jMenu13);
        jMenu2.add(jSeparator1);

        jMenu7.setText("Jornada de Vacunación por animales");

        EJornadaDiarioM5.setText("Diario por Municipio");
        jMenu7.add(EJornadaDiarioM5);

        EJornadaSemanalM5.setText("Semanal por Municipio");
        jMenu7.add(EJornadaSemanalM5);

        EJornadaMensualM5.setText("Mensual por Municipio");
        jMenu7.add(EJornadaMensualM5);
        jMenu7.add(jSeparator9);

        EJornadaDiarioP5.setText("Diario por Parroquia");
        jMenu7.add(EJornadaDiarioP5);

        EJornadaSemanalP5.setText("Semanal por Parroquia");
        jMenu7.add(EJornadaSemanalP5);

        EJornadaMensualP5.setText("Mensual por Parroquia");
        jMenu7.add(EJornadaMensualP5);

        jMenu2.add(jMenu7);

        jMenu11.setText("Jornada de Vacunación por especies");

        EJornadaDiarioM6.setText("Diario por Municipio");
        jMenu11.add(EJornadaDiarioM6);

        EJornadaSemanalM6.setText("Semanal por Municipio");
        jMenu11.add(EJornadaSemanalM6);

        EJornadaMensualM6.setText("Mensual por Municipio");
        jMenu11.add(EJornadaMensualM6);
        jMenu11.add(jSeparator10);

        EJornadaDiarioP6.setText("Diario por Parroquia");
        jMenu11.add(EJornadaDiarioP6);

        EJornadaSemanalP6.setText("Semanal por Parroquia");
        jMenu11.add(EJornadaSemanalP6);

        EJornadaMensualP6.setText("Mensual por Parroquia");
        jMenu11.add(EJornadaMensualP6);

        jMenu2.add(jMenu11);

        menu.add(jMenu2);

        jMenu3.setText("Informes");
        menu.add(jMenu3);

        opciones.setText("Opciones");

        importar.setText("Importar Excel");
        opciones.add(importar);

        exportar.setText("Exportar a Excel");
        opciones.add(exportar);
        opciones.add(jSeparator4);

        acercaDe.setText("Acerca de");
        opciones.add(acercaDe);

        ayuda.setText("Ayuda");
        opciones.add(ayuda);

        menu.add(opciones);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FONDO)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FONDO)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addListeners() {
        jornadasVacunacion.addActionListener(TemplateListeners.getJornadaVacunacionBandeja());
        casos.addActionListener(TemplateListeners.getCasosBandeja());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Application.run(Template.class, args);
    }

    public JDesktopPane getFONDO() {
        return FONDO;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EJornadaDiarioM1;
    private javax.swing.JMenuItem EJornadaDiarioM4;
    private javax.swing.JMenuItem EJornadaDiarioM5;
    private javax.swing.JMenuItem EJornadaDiarioM6;
    private javax.swing.JMenuItem EJornadaDiarioP1;
    private javax.swing.JMenuItem EJornadaDiarioP4;
    private javax.swing.JMenuItem EJornadaDiarioP5;
    private javax.swing.JMenuItem EJornadaDiarioP6;
    private javax.swing.JMenuItem EJornadaMensualM1;
    private javax.swing.JMenuItem EJornadaMensualM4;
    private javax.swing.JMenuItem EJornadaMensualM5;
    private javax.swing.JMenuItem EJornadaMensualM6;
    private javax.swing.JMenuItem EJornadaMensualP1;
    private javax.swing.JMenuItem EJornadaMensualP4;
    private javax.swing.JMenuItem EJornadaMensualP5;
    private javax.swing.JMenuItem EJornadaMensualP6;
    private javax.swing.JMenuItem EJornadaSemanalM1;
    private javax.swing.JMenuItem EJornadaSemanalM4;
    private javax.swing.JMenuItem EJornadaSemanalM5;
    private javax.swing.JMenuItem EJornadaSemanalM6;
    private javax.swing.JMenuItem EJornadaSemanalP1;
    private javax.swing.JMenuItem EJornadaSemanalP4;
    private javax.swing.JMenuItem EJornadaSemanalP5;
    private javax.swing.JMenuItem EJornadaSemanalP6;
    private javax.swing.JDesktopPane FONDO;
    private javax.swing.JMenuItem acercaDe;
    private javax.swing.JMenuItem ayuda;
    private javax.swing.JMenuItem casos;
    private javax.swing.JMenuItem exportar;
    private javax.swing.JMenuItem importar;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenuItem jornadasVacunacion;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem novedades;
    // End of variables declaration//GEN-END:variables
}
